name: coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  report:
    runs-on: Ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r test_requirements.txt
          python -m pip install .
          pip list

      - name: Run tests
        run: |
          pytest -v --pyargs --cov=numpydoc --cov-report xml numpydoc

      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Upload coverage to Codecov'

